language: cpp
dist: bionic

compiler: gcc

addons:
  apt:
    packages: lcov

before_install:
    - sudo apt-get update
    - sudo apt-get -y install cmake build-essential pkg-config libgoogle-perftools-dev wget unzip libgtest-dev
    - mkdir build_gtest
    - cd build_gtest
    - cmake /usr/src/gtest
    - make
    - sudo make install
    - cd ..
    - rm -Rf build_gtest

before_script:
    - mkdir build
    - cd build
    - cmake -DCODE_COVERAGE=ON -DBUILD_TEST=ON -DCMAKE_BUILD_TYPE=Debug ..

script: 
    - make

after_success:
    - ctest -VV
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
    - lcov --list coverage.info # debug info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

