language: cpp
dist: bionic

compiler: gcc

before_install:
    - sudo apt-get update
    - sudo apt-get -y install cmake build-essential pkg-config libgoogle-perftools-dev libboost-all-dev wget unzip

before_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TEST=ON ..

script: 
    - make

after_success:
    - make test

